// <auto-generated />
using EFCore.Migrations.AutoComments.Tests.MigrationTests.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.Migrations.AutoComments.Tests.MigrationTests.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerMigrationDbContext))]
    [Migration("20260428214614_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Идентификатор блога.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Название блога.");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("URL блога.");

                    b.HasKey("Id");

                    b.ToTable("Blogs", t =>
                        {
                            t.HasComment("Блог.");
                        });
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.BlogView", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("blog_view", (string)null);
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Идентификатор.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("PostBase", t =>
                        {
                            t.HasComment("Базовый тип в наследовании TPH.");
                        });

                    b.HasDiscriminator<string>("Discriminator").HasValue("PostBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Идентификатор заказа.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasComment("Категория заказа.");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("int")
                        .HasComment("Способ доставки.");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit")
                        .HasComment("Статус подтверждения заказа.");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Номер заказа.");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("Статус заказа.\n\n0 - Активный, ожидает выполнения.\n1 - Выполнен, доставлен покупателю.\n2 - Отменён, возврат средств.")
                        .HasAnnotation("AutoCommentEnumDescription", "");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Итоговая сумма заказа в рублях.");

                    b.HasKey("Id");

                    b.ToTable("Orders", t =>
                        {
                            t.HasComment("Заказ покупателя.");
                        });
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostA", b =>
                {
                    b.HasBaseType("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostBase");

                    b.Property<string>("TextA")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Текст А.");

                    b.ToTable(t =>
                        {
                            t.HasComment("Базовый тип в наследовании TPH.");
                        });

                    b.HasDiscriminator().HasValue("PostA");
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostB", b =>
                {
                    b.HasBaseType("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostBase");

                    b.Property<string>("TextB")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Текст Б.");

                    b.ToTable(t =>
                        {
                            t.HasComment("Базовый тип в наследовании TPH.");
                        });

                    b.HasDiscriminator().HasValue("PostB");
                });
#pragma warning restore 612, 618
        }
    }
}
