// <auto-generated />
using EFCore.Migrations.AutoComments.Tests.MigrationTests.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.Migrations.AutoComments.Tests.MigrationTests.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerMigrationDbContext))]
    partial class SqlServerMigrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Blog identifier.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Blog name.");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Blog URL.");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasComment("Blog.");
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.BlogView", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("blog_view");
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identifier.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PostBase");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PostBase");

                    b.HasComment("Base type in TPH inheritance.");
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Order identifier.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasComment("Order category.");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("int")
                        .HasComment("Delivery method.");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit")
                        .HasComment("Order confirmation status.");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Order number.");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("Order status.\n\n0 - Active, awaiting fulfillment.\n1 - Completed, delivered to the customer.\n2 - Cancelled, refund issued.")
                        .HasAnnotation("AutoCommentEnumDescription", "");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Total order amount.");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasComment("Customer order.");
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostA", b =>
                {
                    b.HasBaseType("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostBase");

                    b.Property<string>("TextA")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Text A.");

                    b.HasDiscriminator().HasValue("PostA");

                    b.HasComment("Base type in TPH inheritance.");
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostB", b =>
                {
                    b.HasBaseType("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostBase");

                    b.Property<string>("TextB")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Text B.");

                    b.HasDiscriminator().HasValue("PostB");

                    b.HasComment("Base type in TPH inheritance.");
                });
#pragma warning restore 612, 618
        }
    }
}
