// <auto-generated />
using EFCore.Migrations.AutoComments.Tests.MigrationTests.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFCore.Migrations.AutoComments.Tests.MigrationTests.PostgreSQL.Migrations
{
    [DbContext(typeof(PostgreSqlMigrationDbContext))]
    [Migration("20260519191354_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Blog identifier.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasComment("Blog name.");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasComment("Blog URL.");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasComment("Blog.");
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.BlogView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Identifier.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasComment("Name.");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasComment("URL.");

                    b.HasKey("Id");

                    b.ToTable("BlogViews");

                    b.HasComment("Blog view.");
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Identifier.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PostBase");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PostBase");

                    b.HasComment("Base type in TPH inheritance.");
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Order identifier.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasComment("Order category.\n\n0 - Clothing.\n1 - Books.\n2 - Toys.")
                        .HasAnnotation("AutoCommentEnumDescription", "");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("integer")
                        .HasComment("Delivery method.");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean")
                        .HasComment("Order confirmation status.");

                    b.Property<string>("Number")
                        .HasColumnType("text")
                        .HasComment("Order number.");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Order status.\n\n0 - Active, awaiting fulfillment.\n1 - Completed, delivered to the customer.\n2 - Cancelled, refund issued.")
                        .HasAnnotation("AutoCommentEnumDescription", "");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasComment("Total order amount.");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasComment("Customer order.");
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostA", b =>
                {
                    b.HasBaseType("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostBase");

                    b.Property<string>("TextA")
                        .HasColumnType("text")
                        .HasComment("Text A.");

                    b.HasDiscriminator().HasValue("PostA");

                    b.HasComment("Base type in TPH inheritance.");
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostB", b =>
                {
                    b.HasBaseType("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostBase");

                    b.Property<string>("TextB")
                        .HasColumnType("text")
                        .HasComment("Text B.");

                    b.HasDiscriminator().HasValue("PostB");

                    b.HasComment("Base type in TPH inheritance.");
                });
#pragma warning restore 612, 618
        }
    }
}
