// <auto-generated />
using EFCore.Migrations.AutoComments.Tests.MigrationTests.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFCore.Migrations.AutoComments.Tests.MigrationTests.PostgreSQL.Migrations
{
    [DbContext(typeof(PostgreSqlMigrationDbContext))]
    [Migration("20260502205621_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("BlogBaseSequence");

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Blog identifier.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasComment("Blog name.");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasComment("Blog URL.");

                    b.HasKey("Id");

                    b.ToTable("Blogs", t =>
                        {
                            t.HasComment("Blog.");
                        });
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.BlogView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Identifier.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasComment("Name.");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasComment("URL.");

                    b.HasKey("Id");

                    b.ToTable("BlogViews", t =>
                        {
                            t.HasComment("Blog view.");
                        });
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Identifier.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("ArticleBase", t =>
                        {
                            t.HasComment("Base type in TPT inheritance.");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.BlogBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"BlogBaseSequence\"')")
                        .HasComment("Identifier.");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Identifier.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.ToTable("PostBase", t =>
                        {
                            t.HasComment("Base type in TPH inheritance.");
                        });

                    b.HasDiscriminator<string>("Discriminator").HasValue("PostBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Order identifier.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasComment("Order category.\n\n0 - Clothing.\n1 - Books.\n2 - Toys.")
                        .HasAnnotation("AutoCommentEnumDescription", "");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("integer")
                        .HasComment("Delivery method.");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean")
                        .HasComment("Order confirmation status.");

                    b.Property<string>("Number")
                        .HasColumnType("text")
                        .HasComment("Order number.");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Order status.\n\n0 - Active, awaiting fulfillment.\n1 - Completed, delivered to the customer.\n2 - Cancelled, refund issued.")
                        .HasAnnotation("AutoCommentEnumDescription", "");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasComment("Total order amount.");

                    b.HasKey("Id");

                    b.ToTable("Orders", t =>
                        {
                            t.HasComment("Customer order.");
                        });
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleA", b =>
                {
                    b.HasBaseType("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleBase");

                    b.Property<string>("ContentA")
                        .HasColumnType("text")
                        .HasComment("Type A specific content.");

                    b.ToTable("ArticleA", t =>
                        {
                            t.HasComment("TPT derived type A.");
                        });
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleB", b =>
                {
                    b.HasBaseType("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleBase");

                    b.Property<string>("ContentB")
                        .HasColumnType("text")
                        .HasComment("Type B specific content.");

                    b.ToTable("ArticleB", t =>
                        {
                            t.HasComment("TPT derived type B.");
                        });
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.BlogA", b =>
                {
                    b.HasBaseType("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.BlogBase");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasComment("Name A.");

                    b.ToTable("BlogA", t =>
                        {
                            t.HasComment("TPC derived type A.");
                        });
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.BlogB", b =>
                {
                    b.HasBaseType("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.BlogBase");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasComment("Name B.");

                    b.ToTable("BlogB", t =>
                        {
                            t.HasComment("TPC derived type B.");
                        });
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostA", b =>
                {
                    b.HasBaseType("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostBase");

                    b.Property<string>("TextA")
                        .HasColumnType("text")
                        .HasComment("Text A.");

                    b.ToTable(t =>
                        {
                            t.HasComment("Base type in TPH inheritance.");
                        });

                    b.HasDiscriminator().HasValue("PostA");
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostB", b =>
                {
                    b.HasBaseType("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostBase");

                    b.Property<string>("TextB")
                        .HasColumnType("text")
                        .HasComment("Text B.");

                    b.ToTable(t =>
                        {
                            t.HasComment("Base type in TPH inheritance.");
                        });

                    b.HasDiscriminator().HasValue("PostB");
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleA", b =>
                {
                    b.HasOne("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleBase", null)
                        .WithOne()
                        .HasForeignKey("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleA", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleB", b =>
                {
                    b.HasOne("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleBase", null)
                        .WithOne()
                        .HasForeignKey("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleB", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
