// <auto-generated />
using EFCore.Migrations.AutoComments.Tests.MigrationTests.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFCore.Migrations.AutoComments.Tests.MigrationTests.PostgreSQL.Migrations
{
    [DbContext(typeof(PostgreSqlMigrationDbContext))]
    [Migration("20260428213456_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("BlogBaseSequence");

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор блога.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasComment("Название блога.");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasComment("URL блога.");

                    b.HasKey("Id");

                    b.ToTable("Blogs", t =>
                        {
                            t.HasComment("Блог.");
                        });
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.BlogView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasComment("Наименование.");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasComment("URL.");

                    b.HasKey("Id");

                    b.ToTable("BlogViews", t =>
                        {
                            t.HasComment("Представление блога.");
                        });
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("ArticleBase", t =>
                        {
                            t.HasComment("Базовый тип в наследовании TPT.");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.BlogBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"BlogBaseSequence\"')")
                        .HasComment("Идентификатор.");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.ToTable("PostBase", t =>
                        {
                            t.HasComment("Базовый тип в наследовании TPH.");
                        });

                    b.HasDiscriminator().HasValue("PostBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор заказа.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasComment("Категория заказа.\n\n0 - Одежда.\n1 - Книги.\n2 - Игрушки.")
                        .HasAnnotation("AutoCommentEnumDescription", "");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("integer")
                        .HasComment("Способ доставки.");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean")
                        .HasComment("Статус подтверждения заказа.");

                    b.Property<string>("Number")
                        .HasColumnType("text")
                        .HasComment("Номер заказа.");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Статус заказа.\n\n0 - Активный, ожидает выполнения.\n1 - Выполнен, доставлен покупателю.\n2 - Отменён, возврат средств.")
                        .HasAnnotation("AutoCommentEnumDescription", "");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasComment("Итоговая сумма заказа в рублях.");

                    b.HasKey("Id");

                    b.ToTable("Orders", t =>
                        {
                            t.HasComment("Заказ покупателя.");
                        });
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleA", b =>
                {
                    b.HasBaseType("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleBase");

                    b.Property<string>("ContentA")
                        .HasColumnType("text")
                        .HasComment("Специфичное содержимое А.");

                    b.ToTable("ArticleA", t =>
                        {
                            t.HasComment("Наследник А в TPT.");
                        });
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleB", b =>
                {
                    b.HasBaseType("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleBase");

                    b.Property<string>("ContentB")
                        .HasColumnType("text")
                        .HasComment("Специфичное содержимое Б.");

                    b.ToTable("ArticleB", t =>
                        {
                            t.HasComment("Наследник Б в TPT.");
                        });
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.BlogA", b =>
                {
                    b.HasBaseType("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.BlogBase");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasComment("Имя А.");

                    b.ToTable("BlogA", t =>
                        {
                            t.HasComment("Наследник А в TPC.");
                        });
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.BlogB", b =>
                {
                    b.HasBaseType("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.BlogBase");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasComment("Имя Б.");

                    b.ToTable("BlogB", t =>
                        {
                            t.HasComment("Наследник Б в TPC.");
                        });
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostA", b =>
                {
                    b.HasBaseType("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostBase");

                    b.Property<string>("TextA")
                        .HasColumnType("text")
                        .HasComment("Текст А.");

                    b.ToTable(t =>
                        {
                            t.HasComment("Базовый тип в наследовании TPH.");
                        });

                    b.HasDiscriminator().HasValue("PostA");
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostB", b =>
                {
                    b.HasBaseType("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.PostBase");

                    b.Property<string>("TextB")
                        .HasColumnType("text")
                        .HasComment("Текст Б.");

                    b.ToTable(t =>
                        {
                            t.HasComment("Базовый тип в наследовании TPH.");
                        });

                    b.HasDiscriminator().HasValue("PostB");
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleA", b =>
                {
                    b.HasOne("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleBase", null)
                        .WithOne()
                        .HasForeignKey("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleA", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleB", b =>
                {
                    b.HasOne("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleBase", null)
                        .WithOne()
                        .HasForeignKey("EFCore.Migrations.AutoComments.Tests.Models.Inheritance.ArticleB", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
